"skip initialization for vim-tiny or vim-small
if 0 | endif

if &compatible
  set nocompatible
endif
set runtimepath^=${HOME}/.vim/dein.vim

call dein#begin(expand('~/.cache/dein'))

call dein#add('Shougo/neocomplete.vim')
call dein#add('Shougo/neocomplcache.vim')
call dein#add('Shougo/unite.vim')

call dein#end()

filetype plugin indent on
syntax enable

set autoread
set encoding=utf-8
set ignorecase
set mouse=a
set nobackup
set nocompatible
set backspace=indent,eol,start
set noswapfile
set showmatch
set showmode
set termencoding=utf-8

"linenumber
set number

"linebreak
set list

"indent
set autoindent
set smartindent

"tab
set expandtab
set tabstop=4
set softtabstop=4

set ruler
set title
set wildmenu
set wrapscan

set undodir=/home/.vim-undo
